### ISSUE TITLE
Is there a way to disable this temporarily? 

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-clipboard-ocr#3]
as per title. Thanks in advance. Though I assume this repo has been left alone and won't be answered 😅. It's all good.

**Comment by mr-pennyworth** [comment]
You can disable it temporarily by running in terminal:
`launchctl unload ~/Library/LaunchAgents/alfred-clipboard-history-ocr.plist`

To enable it later, run:
`launchctl load -wF ~/Library/LaunchAgents/alfred-clipboard-history-ocr.plist`

It may not be very helpful though. Because, once you enable it, it runs OCR on
all the previous images also. Presently, there is no super-simple way of preventing
the OCR for the images that were copied to the clipboard during the disabled time.

**Comment by yarub123** [comment]
@mr-pennyworth All good. Thank you for that. That should suffice. I hadn't seen your reply so I ended up uninstalling temporarily before reinstalling 🙃. Appreciate you.
